Repository Raindrop-eureka/raindrop-back, pull requests merged in 2025-03, with the labels that each got.

#13 Feature/3 kakao oauth
  .gitignore
  src/main/java/com/example/demo/config/KakaoConfig.java
  src/main/java/com/example/demo/scene/domain/Scene.java
  src/main/java/com/example/demo/user/controller/UserController.java
  src/main/java/com/example/demo/user/domain/User.java
  src/main/java/com/example/demo/user/dto/AddUserRequest.java
  src/main/java/com/example/demo/user/dto/KakaoAuthResponse.java
  src/main/java/com/example/demo/user/dto/KakaoInfoResponse.java
  src/main/java/com/example/demo/user/dto/UserDto.java
  src/main/java/com/example/demo/user/dto/UserInfoResponse.java
  src/main/java/com/example/demo/user/repository/UserRepository.java
  src/main/java/com/example/demo/user/service/UserService.java
Labels: enhancement

#16 Feature/12 데이터베이스 마이그레이션
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/리팩토링.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/pull_request_template.md
  .gitignore
  .gradle/8.13/checksums/checksums.lock
  .gradle/8.13/executionHistory/executionHistory.lock
  .gradle/8.13/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
  build/classes/java/main/com/example/demo/DemoApplication.class
  build/reports/problems/problems-report.html
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Create_user_table.sql
  src/main/resources/db/migration/V2__Create_location_table.sql
  src/main/resources/db/migration/V3__Create_scene_table.sql
  src/main/resources/db/migration/V4__Create_message_table.sql
Labels: enhancement

#17 Develop EC2 배포 테스트용
  .gitignore
  .gradle/8.13/checksums/checksums.lock
  .gradle/8.13/executionHistory/executionHistory.lock
  .gradle/8.13/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/demo.main.iml
  .idea/vcs.xml
  README.md
  build.gradle
  build/classes/java/main/com/example/demo/DemoApplication.class
  build/reports/problems/problems-report.html
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/config/KakaoConfig.java
  src/main/java/com/example/demo/config/SwaggerConfig.java
  src/main/java/com/example/demo/message/domain/Message.java
  src/main/java/com/example/demo/message/dto/MessageCreateRequest.java
  src/main/java/com/example/demo/message/dto/MessageDto.java
  src/main/java/com/example/demo/message/repository/MessageMapper.java
  src/main/java/com/example/demo/message/service/MessageService.java
  src/main/java/com/example/demo/scene/controller/SceneController.java
  src/main/java/com/example/demo/scene/domain/Scene.java
  src/main/java/com/example/demo/scene/dto/SceneCreateRequest.java
  src/main/java/com/example/demo/scene/dto/SceneDto.java
  src/main/java/com/example/demo/scene/dto/SceneUpdateRequest.java
  src/main/java/com/example/demo/scene/dto/SceneUpdateVisibilityRequest.java
  src/main/java/com/example/demo/scene/repository/SceneMapper.java
  src/main/java/com/example/demo/scene/service/SceneService.java
  src/main/java/com/example/demo/user/controller/UserController.java
  src/main/java/com/example/demo/user/domain/User.java
  src/main/java/com/example/demo/user/dto/AddUserRequest.java
  src/main/java/com/example/demo/user/dto/KakaoAuthResponse.java
  src/main/java/com/example/demo/user/dto/KakaoInfoResponse.java
  src/main/java/com/example/demo/user/dto/KakaoLoginRequest.java
  src/main/java/com/example/demo/user/dto/KakaoTokenResponse.java
  src/main/java/com/example/demo/user/dto/UserInfoResponse.java
  src/main/java/com/example/demo/user/repository/UserMapper.java
  src/main/java/com/example/demo/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Create_user_table.sql
  src/main/resources/db/migration/V2__Create_location_table.sql
  src/main/resources/db/migration/V3__Create_scene_table.sql
  src/main/resources/db/migration/V4__Create_message_table.sql
  src/main/resources/schema.sql
Labels: deploy

#28 Feature/12 로케이션 테이블 삭제 기준 마이그레이션 스키마 변경
  README.md
  src/main/resources/db/migration/V5__Update_scene_table.sql
Labels: enhancement

#31 Feature/29 Global Exception 기능 도입
  build.gradle
  src/main/java/com/example/demo/common/dto/ApiResponse.java
  src/main/java/com/example/demo/common/exception/BusinessException.java
  src/main/java/com/example/demo/common/exception/ErrorCode.java
  src/main/java/com/example/demo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/demo/common/exception/ResourceNotFoundException.java
  src/main/java/com/example/demo/common/exception/UnauthorizedException.java
  src/main/java/com/example/demo/config/SwaggerConfig.java
  src/main/java/com/example/demo/message/controller/MessageController.java
  src/main/java/com/example/demo/message/service/MessageService.java
  src/main/resources/application.yml
Labels: enhancement

#39 #38 feat: 로컬 개발환경용 WebConfig 추가
  src/main/java/com/example/demo/config/WebConfig.java
Labels: enhancement, deploy

#42 [BUG] scene 생성시 500 오류 해결
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  Dockerrun.aws.json
  Procfile
  build.gradle
  docker-compose.yml
  src/main/java/com/example/demo/config/WebConfig.java
  src/main/java/com/example/demo/scene/repository/SceneMapper.java
  src/main/java/com/example/demo/scene/service/SceneService.java
  src/main/resources/application.yml.example
  src/main/resources/db/migration/V1__Create_user_table.sql
  src/main/resources/db/migration/V2__Create_scene_table.sql
  src/main/resources/db/migration/V3__Create_message_table.sql
Labels: bug

#43 #41 반영사항 배포
  src/main/java/com/example/demo/scene/repository/SceneMapper.java
  src/main/java/com/example/demo/scene/service/SceneService.java
Labels: bug
